const data = [
  {
    pname: "Mercury",
    ppic: "./images/Planets/mercury.png",
    pbg: "./images/Backgrounds/bmercury.jpg",
    oprice: 76934,
    price: 69987,
    diff: 6947,
  },
  {
    pname: "Venus",
    ppic: "./images/Planets/venus.png",
    pbg: "./images/Backgrounds/bvenus.jpg",
    oprice: 62587,
    price: 56987,
    diff: 5600,
  },
  {
    pname: "Earth",
    ppic: "./images/Planets/earth.png",
    pbg: "./images/Backgrounds/bearth.jpg",
    oprice: 145982,
    price: 135987,
    diff: 9995,
  },
  {
    pname: "Mars",
    ppic: "./images/Planets/mars.png",
    pbg: "./images/Backgrounds/bmars.jpg",
    oprice: 72787,
    price: 61787,
    diff: 11000,
  },
  {
    pname: "Jupiter",
    ppic: "./images/Planets/jupiter.png",
    pbg: "./images/Backgrounds/bvenus.jpg",
    oprice: 119387,
    price: 109987,
    diff: 9400,
  },
  {
    pname: "Saturn",
    ppic: "./images/Planets/saturn.png",
    pbg: "./images/Backgrounds/bmars.jpg",
    oprice: 93687,
    price: 91987,
    diff: 1700,
  },
  {
    pname: "Uranus",
    ppic: "./images/Planets/uranus.png",
    pbg: "./images/Backgrounds/buranus.jpg",
    oprice: 43987,
    price: 42987,
    diff: 1000,
  },
  {
    pname: "Neptune",
    ppic: "./images/Planets/neptune.png",
    pbg: "./images/Backgrounds/bneptune.jpg",
    oprice: 113689,
    price: 111987,
    diff: 1702,
  },
];
